version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/docker1"
      - "/docker2"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
