version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/docker1"
      - "/docker2"
    schedule:
      interval: "daily"
    groups:
      docker-images:
        patterns:
          - "*"
