name: git diff api
on: pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          set +e # dont fail based on grep exit code
          git diff --name-only HEAD~1 | grep --invert-match '.md$'
          if [ $? -eq 0 ]; then
              echo "docs_only=false" >> $GITHUB_OUTPUT
          else
              echo "docs_only=true" >> $GITHUB_OUTPUT
          fi
