name: git diff api
on: pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
        with:
          fetch-depth: 2 # needed to diff changed files
      - id: docs_only_check
        name: Check for docs-only changes
        run: |
          set +e # dont fail based on grep exit code
          git diff --name-only HEAD~1 | grep --ignore-case --invert-match '.md$'
          if [ $? -eq 0 ]; then
              echo "docs_only=false" >> $GITHUB_OUTPUT
          else
              echo "docs_only=true" >> $GITHUB_OUTPUT
          fi
