name: disk
on:
  workflow_dispatch:

permissions: {}

jobs:
  disk:
    runs-on: ubuntu-latest
    steps:
      - run: df -h
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
