name: Run end-to-end tests
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
      - '*.md'
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  generate-model:
    runs-on: ubuntu-latest
    steps:
    - name: generate model
      id: model
      run: |
        set -e
        MODEL_ROOT=$(mktemp --directory)
        echo "root=$MODEL_ROOT" >> "$GITHUB_OUTPUT"
        for i in {0..1}; do
            DIR="${MODEL_ROOT}/d${i}"
            mkdir "$DIR"
            for j in {0..2}; do
                echo "This is file f${i}${j} in d${i}." > "${DIR}/f${i}${j}"
            done
        done
        for i in {0..3}; do
            echo "This is file f${i} in root." > "${MODEL_ROOT}/f${i}"
        done
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        path: ${{ steps.model.outputs.root }}
        name: model.zip
        if-no-files-found: error
        retention-days: 1
  model-signing:
    name: Signing with ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    needs: [generate-model]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Download model
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: model.zip
        path: model_root/
    - name: Sign the model
      run: find model_root/
