name: test ref

# permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  foo:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BRANCH: ${{ github.repository.default_branch }}
      REF: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - run: echo $DEFAULT_BRANCH $REF ${{ toJson(github) }}
