name: test ref

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# bar
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }} # head SHA if PR, else fallback to push SHA
