name: token
on:
  workflow_dispatch:

permissions: {}

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -sS -f -I -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com
